config/routes.rb
Datestar::Application.routes.draw do

  resources :users do
    resources :photos, :only => [:create, :destroy]
  end

  match '/photo' => 'photos#index', :via => :get, :as => :photos
  match '/photo' => 'photos#create', :via => :post

  match '/login' => 'session#new', :via => :get
  match '/login' => 'session#create', :via => :post
  match '/logout' => 'session#destroy', :via => :get

  match '/question' => 'questions#index', :via => :get, :as => :questions
  match '/question' => 'questions#create', :via => :post

  match '/answer' => 'answers#index', :via => :get, :as => :answers
  match '/answer' => 'answers#create', :via => :post

  match '/match/:id' => 'match#index', :via => :get, :as => 'match'
  match '/match/:id' => 'match#check', :via => :post
  match '/match/show/:id' => 'match#show', :via => :get, :as => 'match_show'

  match '/message/:id' => 'messages#index', :via => :get, :as => 'messages'
  match '/message/:id' => 'messages#create', :via => :post, :as => 'write'
  match '/sent/:id' => 'messages#sent', :via => :get, :as => 'sent'
  match '/inbox/:id' => 'messages#inbox', :via => :get, :as => 'inbox'

  root :to => 'welcome#index'

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer
#  answer1     :string(255)
#  answer2     :string(255)
#  answer3     :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ActiveRecord::Base
	belongs_to :question

end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id          :integer          not null, primary key
#  sender_id   :integer
#  receiver_id :integer
#  match       :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Match < ActiveRecord::Base

	belongs_to :metoyou, foreign_key: 'sender_id', class_name: 'User'
	belongs_to :youtome, foreign_key: 'receiver_id', class_name: 'User'

	# belongs_to :user, :foreign_key => 'receiver_id'
 	# belongs_to :sender, class_name: 'User'
 	# belongs_to :receiver, class_name: 'User'
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, foreign_key: 'sender_id', class_name: 'User'
	belongs_to :receiver, foreign_key: 'receiver_id', class_name: 'User'
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Photo < ActiveRecord::Base
	belongs_to :user
	storage :fog

	mount_uploader :photo, PhotoUploader
	default_scope order(:id)
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  question   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  password_digest :string(255)
#  tagline         :string(255)
#  main_pic_id     :integer
#  age             :integer
#  gender          :string(255)
#  city            :string(255)
#  state           :string(255)
#  ethnicity       :string(255)
#  description     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
	has_many :photos
  has_many :questions
	has_secure_password

 	has_many :initiator, foreign_key: 'sender_id', class_name: 'Match'
 	has_many :initiated, foreign_key: 'receiver_id', class_name: 'Match'

 	has_many :sendd, foreign_key: 'sender_id', class_name: 'Message'
 	has_many :receive, foreign_key: 'receiver_id', class_name: 'Message'

 	# has_many :matched_users, through: :matches, source: 'receiver'
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_filter :authenticate_user

	def index
		@a = Answer.new
	end

	def create

		@a = Answer.new(params[:answer])

		if @a.save
			redirect_to users_path
		else
			render :index
		end

	end
	def destroy

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user
  private
  def authenticate_user
  	if session[:user_id]
  		@authenticated_user = User.find(session[:user_id])
  	else
  		@authenticated_user = nil
  	end
  end
end

app/controllers/match_controller.rb
class MatchController < ApplicationController
	def index
		user_id = params[:id]
		@receiver = User.find(user_id)
		@q = Question.where(:user_id => @receiver.id).sample
		@a = Answer.where(:question_id => @q.id)
  	end
  	def check
			@r = params[:receiver]
			@q = params[:question]
  		@choice = params[:answer]

  		if @authenticated_user && @choice == Answer.find_by_question_id(@q).answer1
  			m = Match.new
  			m[:sender_id] = @authenticated_user.id
  			m[:receiver_id] = @r.to_i
  			m[:match] = 1
  			m.save
  			redirect_to write_path
  		else
  			m = Match.new
  			m[:sender_id] = @authenticated_user.id
  			m[:receiver_id] = @r.to_i
  			m[:match] = 0
  			m.save
  			redirect_to users_path
  		end
  	end
    def show
      user_id = params[:id]
      @me_to_you = User.find(user_id).initiator
      @you_to_me = User.find(user_id).initiated
      @user = User.find(user_id)
    end
end

app/controllers/messages_controller.rb
class	MessagesController < ApplicationController
	def index
		user_id = params[:id]
		@receiver = User.find(user_id)
		@message = Message.new
	end
	def create
		m = Message.new(params[:message])
		m[:sender_id] = @authenticated_user.id
		m[:receiver_id] = params[:receiver_id]
		if @authenticated_user && m.save
			redirect_to user_path
		else
			render :index
		end
	end
	def inbox
		user_id = params[:id]
		@inbox = User.find(user_id).receive
		@sentbox = User.find(user_id).sendd
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user

	def index
		@p = Photo.new
	end

	def create
		# raise params.inspect

		user_id = params[:photo][:user_id]
		@user = User.find(user_id)
		@photo = Photo.new(params[:photo])

		if @photo.save
			redirect_to @user
		else
			render :index
		end

	end
	def destroy

	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :authenticate_user

	def index
		@question = Question.new
	end

	def create
		@question = Question.new(params[:question])
		if @question.save
			redirect_to answers_path
		else
			render :index
		end

	end
	def destroy

	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
	end
	def create

			@user = User.find_by_name(params[:name])

			if @user && @user.authenticate(params[:password])
					session[:user_id] = @user.id
					redirect_to users_path
			else
				render :new
			end
	end
	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(params[:user])

		if @user.save
			redirect_to users_path
		else
			render :new
		end

	end
	def show
		user_id = params[:id]
		@user = User.find(user_id)
		@p = Photo.new

		if (@authenticated_user == @user)
			@show = false
			@matched = false
		elsif (Match.where(:sender_id => @authenticated_user, :receiver_id => @user).empty?)
			@show = true
			@matched = false
		elsif (Match.where(:sender_id => @authenticated_user, :receiver_id => @user).first.match)
			@show = false
			@matched = true
		elsif !(Match.where(:sender_id => @authenticated_user, :receiver_id => @user).first.match)
			@show = false
			@matched = false
		end
	end
	def edit
		user_id = params[:id]
		@user = User.find(user_id)
	end
	def update
		@user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
		def show_dynamic_links
			if @authenticated_user
				link_to @authenticated_user.name, logout_path
			else
				link_to 'Login', login_path
			end

		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/index.html.erb
<p>All it takes is <strong>one</strong> right answer!</p>

<ul class="nav nav-list">
	<li class="divider"></li> 
</ul>


<div id="container_logged_in">

	<div class = "content">
		<div id="answers"></div>
	</div>

	<div class = "divider_box">
	</div>
	<div class="answer">
		<%= form_for @a do |f| %>
			<%= f.label :correct_answer %>
			<%= f.text_field :answer1 %>

			<%= f.label :fake_answer %>
			<%= f.text_field :answer2 %>

			<%= f.label :fake_answer %>
			<%= f.text_field :answer3 %>

			<%= f.hidden_field :question_id, :value => (Question.where(:user_id => @authenticated_user.id).last if @authenticated_user).id %>

			<%= f.submit 'Save', class: "btn" %>
		<% end %>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datestar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
</head>
<body>
	<header>
		<div id="logo"><%= link_to image_tag('logo-01.png'), root_path %></div>
		<nav >
			<strong>
				<%= show_dynamic_links %>
				<%= link_to "MY PROFILE", user_path(@authenticated_user) if @authenticated_user %>
				<%= link_to "USERS", users_path if @authenticated_user %>
				<%= link_to "NEW USER", new_user_path if !@authenticated_user %>
				<%= link_to "NEW QUESTION", questions_path(@authenticated_user) if @authenticated_user %>
				<%= link_to "MY MATCHES", match_show_path(@authenticated_user) if @authenticated_user %>
				<%= link_to "MY INBOX", inbox_path(@authenticated_user)  if @authenticated_user %>
			</strong>
		</nav>
	</header>

	<div class="main">
		<%= yield %>
	</div>

	<footer>
		<div id="copyrights">
			© 2012 <strong>cutie.pie</strong> :: All rights reserved ::
			Made by Hand. [<span class="heart">&#x2665;</span>]
		</div>

		<div id="social-media" class="clearfix">
			<ul>
				<li><a href="#" class="facebook">Facebook</a></li>
				<li><a href="#" class="twitter">Twitter</a></li>	
			</ul>
		</div><!-- #social-media -->
	</footer>

</body>
</html>

app/views/match/check.html.erb
<%= @choice %>

app/views/match/index.html.erb
<p>
	You want to send <strong><%= @receiver.name %></strong> a love note?<br><em>Answer one simple question :-)</em><br>
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>
<br>



<div id="match_question">
	<div class="box">

		<h2><%= @q.question  %></h2>
		<br>

<%= form_tag do %>
<%= hidden_field_tag 'question', @q.id %>
<%= hidden_field_tag 'receiver', @receiver.id %>
<!-- loop here to randomize -->

<% array = [] %>
<% array << @a[0].answer1 << @a[0].answer2 << @a[0].answer3 %>
<% array = array.shuffle %>

	<%= radio_button_tag 'answer', array[0], false %><%= array[0] %><br>
	<%= radio_button_tag 'answer', array[1], false %><%= array[1] %><br>
	<%= radio_button_tag 'answer', array[2], false %><%= array[2] %><br>
	<br>
	<%= submit_tag 'Try your luck!', class: "btn" %>
<% end %>
	</div>
</div>

app/views/match/show.html.erb
<p>
	<strong>Love</strong> is a smoke and is made with the fume of sighs.<br><em> Shakespeare</em>
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>
<br>
<div id="images">
	<div id="seventeen" class="images"></div>
	<div id="sixteen" class="images"></div>
	<div id="nineteen" class="images"></div>
	<div id="three" class="images"></div>
	<div id="twenty" class="images"></div>
	<div id="eighteen" class="images"></div>
	<div id="twelve" class="images"></div>
	<div id="seven" class="images"></div>
</div>
<br>

<h1>[People I liked]</h1><hr>
<br>
<% @me_to_you.each do |m| %>

	<strong>From: </strong> <%= m.metoyou.name %><br>
	<strong>To: </strong><%= m.youtome.name %><br>
	<strong>Match? </strong><%= m.match %><br>
	<hr>
<% end %><br><br>

<h1>[People who liked me]</h1><hr>
<br>
<% @you_to_me.each do |m| %>

	<strong>From: </strong><%= m.metoyou.name %><br>
	<strong>To: </strong><%= m.youtome.name %><br>
	<strong>Match? </strong> <%= m.match %><br>
	<hr>
<% end %><br><br>

<h1>[My Questions]</h1><hr>
<br>

<% @user.questions.each do |q|  %>
<li><%= q.question %></li>
<% end %>

app/views/messages/inbox.html.erb
<p>
	I pray you, do not fall in <strong>love</strong> with me, For I am falser than vows made in <strong>wine</strong>.<br><em> Shakespeare</em>
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>
<br>

<div id="images">
	<div id="nine" class="images"></div>
	<div id="ten" class="images"></div>
	<div id="eleven" class="images"></div>
	<div id="twelve" class="images"></div>
	<div id="thirteen" class="images"></div>
	<div id="fourteen" class="images"></div>
	<div id="fifteen" class="images"></div>
	<div id="sixteen" class="images"></div>
</div>
<br>
<h1>[Inbox]</h1><hr>
<br>
<% @inbox.each do |m| %>

	<strong>From:</strong> <%= m.sender.name %><br>
	<strong>To:</strong> <%= m.receiver.name %><br>
	<strong>Subject:</strong> <%= m.subject %><br>
	<strong>Message:</strong> <%= m.message %><br>
	<hr>
<% end %><br><br>

<h1>[Sent Messages]</h1><hr>
<br>
<% @sentbox.each do |m| %>
	<strong>From:</strong> <%= m.sender.name %><br>
	<strong>To:</strong> <%= m.receiver.name %><br>
	<strong>Subject:</strong> <%= m.subject %><br>
	<strong>Message:</strong> <%= m.message %><br>
	<hr>
<% end %>

app/views/messages/index.html.erb
<p>
	My analyst warned me, but you were so <strong>beautiful</strong> I got another analyst.<br><em> Woody Allen</em>
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>
<br>



<div id="private_message">
	<div class="box">
		<h2>Send a private message! [<span class="heart">&#x2665;</span>]</h2>
		<%= form_for @message do |f| %>
			<%= f.label :subject %>
			<%= f.text_field :subject, class: "input-xxlarge" %>
			<%= f.label :message %>
			<%= f.text_area :message, class: "input-xxlarge" %>
			<%= hidden_field_tag 'receiver_id', @receiver.id %>
			<br>
			<%= f.submit 'Send!', class: "btn" %>
		<% end %>
	</div>
</div>

app/views/questions/index.html.erb
<p>All it takes is <strong>one</strong> right answer!</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>

<div id="container_logged_in">

	<div class="content">
		<div></div>
	</div>


	<div class="question">
		<%= form_for @question do |f| %>
			<%= f.label :question %>
			<%= f.text_field :question %>
			<%= f.hidden_field :user_id, :value => @authenticated_user.id if @authenticated_user %>
			<br>
			<%= f.submit 'Save', class: "btn" %>
		<% end %>
	</div>
</div>

app/views/session/new.html.erb
<p>
	No one looks back at their <strong>life</strong> and remembers the nights they had plenty of sleep
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>
<div id="first_login">
	<div class = "box_login">
		<%= form_tag '/login' do %>
			<div class="field_login">
				<p>Name:</p>
				<%= text_field_tag "name" %>
			</div>
			<div class="field_login">
				<p>Password: </p>
				<%= password_field_tag 'password' %>
			</div>
			<div class="actions">
		        <%= submit_tag "Login!", class: "btn" %>
		    </div>
		<% end %>
	</div>	
</div>

app/views/users/_form.html.erb
<p>
  Enter your deets &amp; we'll find your <strong>perfect</strong> cutie<strong>.</strong>pie
</p><hr>

  <div id="user-login">

 
      <%= form_for @user do |f| %>
      <div class="box_1">
           <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>
          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="field">
            <%= f.label :Profile_picture %><br />
            <%= f.text_field :main_pic_id %>
          </div>
          <div class="field">
            <%= f.label :Tag_Line %><br />
            <%= f.text_field :tagline %>
          </div>
          <div class="field">
            <%= f.label :Age %><br />
            <%= f.text_field :age %>
          </div>
        </div>
        <div class="box_1">
          <div class="field">
            <%= f.label :gender %><br />
            <%= f.text_field :gender %>
          </div>
          <div class="field">
            <%= f.label :city %><br />
            <%= f.text_field :city %>
          </div>
          <div class="field">
            <%= f.label :state %><br />
            <%= f.text_field :state %>
          </div>
          <div class="field">
            <%= f.label :ethnicity %><br />
            <%= f.text_field :ethnicity %>
          </div>
          <div class="field">
            <%= f.label :description %><br />
            <%= f.text_field :description %>
          </div>

          <div class="actions">
          <%= f.submit "Let's do this!", class: "btn" %>
         </div>
       </div>
       <div class="box_2">
        <div></div>
       </div>

  <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<p>
	<strong>Life </strong>is one fool thing after another. <br>Where as <strong> love </strong> is two fool things after each.<br><em> Oscar Wilde</em>
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>

<div id="users-layout">
	<div class="box">
		<% @users.each do |u| %>
		<div id="user">
			<%= link_to u.name, u %> <br>
			<%#= image_tag u.photos[u[:main_pic_id]].photo if !(u.photos.empty?) %>
		</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p>
	Who ever <strong>loved</strong> that <strong>loved</strong> not at first sight?<em> Shakespeare</em>
</p>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>
<div class = "profile_container">
	<div class = "profile_1">
		<div class = "profile_info">
				<h1> <%= @user.name %> </h1>
				<div class="f1"><strong>Tagline:</strong> <%= @user.tagline %> </div>
				<div class="f1"><strong>Age:</strong> <%= @user.age %></div>
				<div class="f1"><strong>Gender:</strong> <%= @user.gender %></div>
				<div class="f1"><strong>Location:</strong></div>
				<div class="f1"> <%= @user.city + ' , ' + @user.state %></div>
				<div class="f1"><strong>Ethnicity:</strong> <%= @user.ethnicity %></div>
				<div class="f1"><strong>Description:</strong></div>
				<div class="f1"> <%= @user.description %></div>
				<br>
				<em><%= link_to 'Edit Profile', edit_user_path if @authenticated_user == @user %></em>
		</div>
	</div>

	<div class = "photo_upload">
		<div class="f3">Profile Picture</div>

	</div>

</div>

<div class = "send_message">
	<%= link_to 'Message Me!',  match_path, class: "btn clearfix" if @show %>
	<%= link_to 'Message Me!',  write_path, class: "btn clearfix" if @matched %>
</div>

<hr><br>

<div class = "pictures">
		<h2><%= @user.name %>'s pictures...[<span class="heart">&#x2665;</span>]</h2>
	<br>
	<% @user.photos.each do |p| %>
	<%= image_tag p.photo.thumb %>
	<% end %>

	<div class = "photo_form">
			<%= form_for @p, html: {multipart: true} do |f| %>
				<%= f.label :photo if (@authenticated_user == @user) %>
				<%= f.file_field :photo  if (@authenticated_user == @user) %>
				<%= f.text_field :remote_photo_url if (@authenticated_user == @user) %>
				<%= f.hidden_field :user_id, :value => @authenticated_user.id if @authenticated_user %>
		 		<%= f.submit :upload, class: "btn"  if (@authenticated_user == @user) %>
			<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<p>Someone you haven't even met is wondering what it'd be like to know someone like <strong>you</strong>

<ul class="nav nav-list">
	<li class="divider"></li>
</ul>

<div id="signup">
	<div class="box">
		<strong><%= link_to "Signup For Free!", new_user_path %></strong>
	</div>
</div>

<div id="images">
	<div id="one" class="images"></div>
	<div id="two" class="images"></div>
	<div id="three" class="images"></div>
	<div id="four" class="images"></div>
	<div id="five" class="images"></div>
	<div id="six" class="images"></div>
	<div id="seven" class="images"></div>
	<div id="eight" class="images"></div>
<!-- 	<div id="nine" class="images"></div>
	<div id="ten" class="images"></div>
	<div id="eleven" class="images"></div> -->
</div>

<div id="how-it-works">
	<div id = "container">
		<div id="blurb1">
		</div>
		<div id="blurb2">
		</div>
		<div id="blurb3">
		</div>
	</div>
</div>